# Generated by Django 4.2.5 on 2023-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
